import Img1 from '../assets/11.jpg';
import Img2 from '../assets/12.jpg';
import Img3 from '../assets/13.jpg';
import Img4 from '../assets/16.jpg';
import Img5 from '../assets/31.jpg';
import Img6 from '../assets/33.jpg';
import Img7 from '../assets/36.jpg';
import Img8 from '../assets/41.jpg';
import Img9 from '../assets/44.jpg';
import Img10 from '../assets/47.jpg';
import Img11 from '../assets/52.jpg';
import Img12 from '../assets/56.jpg';
import Img13 from '../assets/62.jpg';
import Img14 from '../assets/64.jpg';
import Img15 from '../assets/67.jpg';
import Img16 from '../assets/69.jpg';

const randomOrders = () => Math.floor(Math.random() * 16) + 15;

const products = [
  {
    id: 1,
    name: "Sugar Plain Putharekulu",
    price: 349,
    originalPrice: Math.round(349 * 1.2),
    category: "putharekulu",
    description: "Traditional sweet with sugar layers, made with love.",
    image: Img9,
    moreImages: [Img9, Img9, Img9],
    ordersLastWeek: randomOrders(),
    topSeller: true,
  },
  {
    id: 2,
    name: "Jaggery Plain Putharekulu",
    price: 349,
    originalPrice: Math.round(349 * 1.2),
    category: "putharekulu",
    description: "Delightful blend of jaggery and tradition.",
    image: Img8,
    moreImages: [Img8, Img8, Img8],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 3,
    name: "Sugar Dryfruits Putharekulu",
    price: 449,
    originalPrice: Math.round(449 * 1.2),
    category: "putharekulu",
    description: "Stuffed with premium dry fruits and sweet sugar.",
    image: Img10,
    moreImages: [Img10, Img10, Img10],
    ordersLastWeek: randomOrders(),
    topSeller: true,
  },
  {
    id: 4,
    name: "Jaggery Dryfruits Putharekulu",
    price: 449,
    originalPrice: Math.round(449 * 1.2),
    category: "putharekulu",
    description: "Wholesome jaggery with dry fruits inside.",
    image: Img3,
    moreImages: [Img3, Img3, Img3],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 5,
    name: "Chocolate Dryfruits Putharekulu",
    price: 499,
    originalPrice: Math.round(499 * 1.2),
    category: "putharekulu",
    description: "A chocolaty twist to a traditional treat.",
    image: Img12,
    moreImages: [Img12, Img12, Img12],
    ordersLastWeek: randomOrders(),
    topSeller: true,
  },
  {
    id: 6,
    name: "Horlicks Dryfruits Putharekulu",
    price: 499,
    originalPrice: Math.round(499 * 1.2),
    category: "putharekulu",
    description: "Malted health with a festive taste.",
    image: Img14,
    moreImages: [Img14, Img14, Img14],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 7,
    name: "Boost Dryfruits Putharekulu",
    price: 499,
    originalPrice: Math.round(499 * 1.2),
    category: "putharekulu",
    description: "Get boosted with our sweet and nutty delight.",
    image: Img13,
    moreImages: [Img13, Img13, Img13],
    ordersLastWeek: randomOrders(),
    topSeller: true,
  },
  {
    id: 8,
    name: "Oreo Dryfruits Putharekulu",
    price: 499,
    originalPrice: Math.round(499 * 1.2),
    category: "putharekulu",
    description: "Fusion of Oreo crunch and dry fruits goodness.",
    image: Img15,
    moreImages: [Img15, Img15, Img15],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 9,
    name: "Kova Dryfruits Putharekulu",
    price: 549,
    originalPrice: Math.round(549 * 1.2),
    category: "putharekulu",
    description: "Rich kova wrapped in crunchy sweet layers.",
    image: Img11,
    moreImages: [Img11, Img11, Img11],
    ordersLastWeek: randomOrders(),
    topSeller: true,
  },
  {
    id: 10,
    name: "Honey Dryfruits Putharekulu",
    price: 549,
    originalPrice: Math.round(549 * 1.2),
    category: "putharekulu",
    description: "Sweetened with nature's own nectar and dry fruits.",
    image: Img1,
    moreImages: [Img1, Img1, Img1],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 11,
    name: "Dates Dryfruits Putharekulu",
    price: 549,
    originalPrice: Math.round(549 * 1.2),
    category: "putharekulu",
    description: "Medjool dates meet Andhra’s iconic sweet.",
    image: Img4,
    moreImages: [Img4, Img4, Img4],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 12,
    name: "Org Palm-Jaggery Putharekulu",
    price: 599,
    originalPrice: Math.round(599 * 1.2),
    category: "putharekulu",
    description: "Unrefined and organic palm jaggery delight.",
    image: Img16,
    moreImages: [Img16, Img16, Img16],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 13,
    name: "Sugarfree Dryfruits Putharekulu",
    price: 599,
    originalPrice: Math.round(599 * 1.2),
    category: "putharekulu",
    description: "Health-conscious version of a festive favorite.",
    image: Img2,
    moreImages: [Img2, Img2, Img2],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 14,
    name: "Sugar Mango Jelly",
    price: 399,
    originalPrice: Math.round(399 * 1.2),
    category: "jellies",
    description: "Mango jelly with sweetened sugar burst.",
    image: Img7,
    moreImages: [Img7, Img7, Img7],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 15,
    name: "Jaggery (Bellam) Mango Jelly",
    price: 399,
    originalPrice: Math.round(399 * 1.2),
    category: "jellies",
    description: "Mango jelly fused with traditional bellam taste.",
    image: Img5,
    moreImages: [Img5, Img5, Img5],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
  {
    id: 16,
    name: "Palm Jelly (Thati Thandra)",
    price: 449,
    originalPrice: Math.round(449 * 1.2),
    category: "jellies",
    description: "Rare treat made with thati thandra (palm jelly).",
    image: Img6,
    moreImages: [Img6, Img6, Img6],
    ordersLastWeek: randomOrders(),
    topSeller: false,
  },
];


export default products;
